/*
 * ParaSwap API v5
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@paraswap.io
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContractMethod {
    #[serde(rename = "swapOnUniswap")]
    SwapOnUniswap,
    #[serde(rename = "buyOnUniswap")]
    BuyOnUniswap,
    #[serde(rename = "swapOnUniswapFork")]
    SwapOnUniswapFork,
    #[serde(rename = "buyOnUniswapFork")]
    BuyOnUniswapFork,
    #[serde(rename = "swapOnUniswapV2Fork")]
    SwapOnUniswapV2Fork,
    #[serde(rename = "buyOnUniswapV2Fork")]
    BuyOnUniswapV2Fork,
    #[serde(rename = "simpleBuy")]
    SimpleBuy,
    #[serde(rename = "simpleSwap")]
    SimpleSwap,
    #[serde(rename = "multiSwap")]
    MultiSwap,
    #[serde(rename = "megaSwap")]
    MegaSwap,
    #[serde(rename = "protectedMultiSwap")]
    ProtectedMultiSwap,
    #[serde(rename = "protectedMegaSwap")]
    ProtectedMegaSwap,
    #[serde(rename = "protectedSimpleSwap")]
    ProtectedSimpleSwap,
    #[serde(rename = "protectedSimpleBuy")]
    ProtectedSimpleBuy,
    #[serde(rename = "swapOnZeroXv2")]
    SwapOnZeroXv2,
    #[serde(rename = "swapOnZeroXv4")]
    SwapOnZeroXv4,
    #[serde(rename = "buy")]
    Buy,

}

impl ToString for ContractMethod {
    fn to_string(&self) -> String {
        match self {
            Self::SwapOnUniswap => String::from("swapOnUniswap"),
            Self::BuyOnUniswap => String::from("buyOnUniswap"),
            Self::SwapOnUniswapFork => String::from("swapOnUniswapFork"),
            Self::BuyOnUniswapFork => String::from("buyOnUniswapFork"),
            Self::SwapOnUniswapV2Fork => String::from("swapOnUniswapV2Fork"),
            Self::BuyOnUniswapV2Fork => String::from("buyOnUniswapV2Fork"),
            Self::SimpleBuy => String::from("simpleBuy"),
            Self::SimpleSwap => String::from("simpleSwap"),
            Self::MultiSwap => String::from("multiSwap"),
            Self::MegaSwap => String::from("megaSwap"),
            Self::ProtectedMultiSwap => String::from("protectedMultiSwap"),
            Self::ProtectedMegaSwap => String::from("protectedMegaSwap"),
            Self::ProtectedSimpleSwap => String::from("protectedSimpleSwap"),
            Self::ProtectedSimpleBuy => String::from("protectedSimpleBuy"),
            Self::SwapOnZeroXv2 => String::from("swapOnZeroXv2"),
            Self::SwapOnZeroXv4 => String::from("swapOnZeroXv4"),
            Self::Buy => String::from("buy"),
        }
    }
}

impl Default for ContractMethod {
    fn default() -> ContractMethod {
        Self::SwapOnUniswap
    }
}




