/*
 * ParaSwap API v5
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@paraswap.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse200 {
    #[serde(rename = "priceRoute", skip_serializing_if = "Option::is_none")]
    pub price_route: Option<serde_json::Value>,
    // Parse price route as raw json to ensure it is not modified between api calls
    // pub price_route: Option<Box<crate::models::PriceRoute>>,
}

impl InlineResponse200 {
    pub fn new() -> InlineResponse200 {
        InlineResponse200 {
            price_route: None,
        }
    }
}


