/*
 * ParaSwap API v5
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@paraswap.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimalSwapExchange {
    #[serde(rename = "exchange")]
    pub exchange: String,
    #[serde(rename = "srcAmount")]
    pub src_amount: String,
    #[serde(rename = "destAmount")]
    pub dest_amount: String,
    #[serde(rename = "percent")]
    pub percent: f32,
    #[serde(rename = "poolAddresses")]
    pub pool_addresses: Option<Vec<String>>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl OptimalSwapExchange {
    pub fn new(exchange: String, src_amount: String, dest_amount: String, percent: f32) -> OptimalSwapExchange {
        OptimalSwapExchange {
            exchange,
            src_amount,
            dest_amount,
            percent,
            pool_addresses: None,
            data: None,
        }
    }
}


