/*
 * ParaSwap API v5
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@paraswap.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct OptimalRoute {
    #[serde(rename = "percent")]
    pub percent: f32,
    #[serde(rename = "swaps")]
    pub swaps: Vec<crate::models::OptimalSwap>,
}

impl OptimalRoute {
    pub fn new(percent: f32, swaps: Vec<crate::models::OptimalSwap>) -> OptimalRoute {
        OptimalRoute {
            percent,
            swaps,
        }
    }
}


