/*
 * ParaSwap API v5
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@paraswap.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimalSwap {
    #[serde(rename = "srcToken")]
    pub src_token: String,
    #[serde(rename = "srcDecimals")]
    pub src_decimals: i32,
    #[serde(rename = "destToken")]
    pub dest_token: String,
    #[serde(rename = "destDecimals")]
    pub dest_decimals: i32,
    #[serde(rename = "swapExchanges")]
    pub swap_exchanges: Vec<crate::models::OptimalSwapExchange>,
}

impl OptimalSwap {
    pub fn new(src_token: String, src_decimals: i32, dest_token: String, dest_decimals: i32, swap_exchanges: Vec<crate::models::OptimalSwapExchange>) -> OptimalSwap {
        OptimalSwap {
            src_token,
            src_decimals,
            dest_token,
            dest_decimals,
            swap_exchanges,
        }
    }
}


