/*
 * ParaSwap API v5
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@paraswap.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceRouteWithError {
    #[serde(rename = "error")]
    pub error: Error,
    /// price impact %
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "priceRoute")]
    pub price_route: Box<crate::models::PriceRoute>,
}

impl PriceRouteWithError {
    pub fn new(error: Error, value: String, price_route: crate::models::PriceRoute) -> PriceRouteWithError {
        PriceRouteWithError {
            error,
            value,
            price_route: Box::new(price_route),
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "ESTIMATED_LOSS_GREATER_THAN_MAX_IMPACT")]
    EstimatedLossGreaterThanMaxImpact,
}

impl Default for Error {
    fn default() -> Error {
        Self::EstimatedLossGreaterThanMaxImpact
    }
}

