/*
 * ParaSwap API v5
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@paraswap.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceError {
    #[serde(rename = "error")]
    pub error: crate::models::PriceErrorMessage,
}

impl PriceError {
    pub fn new(error: crate::models::PriceErrorMessage) -> PriceError {
        PriceError {
            error,
        }
    }
}


