/*
 * ParaSwap API v5
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@paraswap.io
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SwapSide {
    #[serde(rename = "SELL")]
    Sell,
    #[serde(rename = "BUY")]
    Buy,

}

impl ToString for SwapSide {
    fn to_string(&self) -> String {
        match self {
            Self::Sell => String::from("SELL"),
            Self::Buy => String::from("BUY"),
        }
    }
}

impl Default for SwapSide {
    fn default() -> SwapSide {
        Self::Sell
    }
}




