/*
 * ParaSwap API v5
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@paraswap.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionsError {
    #[serde(rename = "error")]
    pub error: crate::models::TransactionsErrorMessage,
}

impl TransactionsError {
    pub fn new(error: crate::models::TransactionsErrorMessage) -> TransactionsError {
        TransactionsError {
            error,
        }
    }
}


