#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod bytes_lib;
pub mod configurator_input_types;
pub mod constants;
pub mod context;
pub mod data_types;
pub mod erc20;
pub mod i_aave_oracle;
pub mod i_augustus;
pub mod i_augustus_registry;
pub mod i_flash_loan;
pub mod i_flash_loan_receiver;
pub mod i_liquidator_paraswap;
pub mod i_pool;
pub mod i_pool_addresses_provider;
pub mod i_pool_configurator;
pub mod i_pool_data_provider;
pub mod i_quoter_v2;
pub mod i_uniswap_v3_flash_callback;
pub mod i_uniswap_v3_pool_actions;
pub mod i_uniswap_v3_swap_callback;
pub mod ierc20;
pub mod ierc20_metadata;
pub mod ierc20_permit;
pub mod il2_encoder;
pub mod il2_pool;
pub mod liquidator;
pub mod liquidator_paraswap;
pub mod mock_aggregator;
pub mod mock_oracle;
pub mod mock_para_swap_token_transfer_proxy;
pub mod ownable;
pub mod owned;
pub mod path;
pub mod pool_address;
pub mod safe_erc20;
pub mod shared_types;
