[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# Must set evm version to paris since solc > 0.8.20 uses op code PUSH0
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
